AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an Amazon Bedrock Knowledge Base and Data Source for a Redshift Serverless workgroup, enabling query engine functionality.

Parameters:
  KnowledgeBaseName:
    Type: String
    Description: Name of the Bedrock knowledge base
    Default: MyKnowledgeBase
    MinLength: 1
    MaxLength: 100
  DataSourceName:
    Type: String
    Description: Name of the Bedrock data source
    Default: MyRedshiftDataSource
    MinLength: 1
    MaxLength: 100
  DatabaseName:
    Type: String
    Description: The name of the Redshift database in the existing namespace
    Default: dev
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  WorkgroupArn:
    Type: String
    Description: ARN of the existing Redshift Serverless workgroup
    Default: arn:aws:redshift-serverless:us-west-2:80216656xxxx:workgroup/bb3671b3-e227-4684-8bd3-00df8c413baa
  AccountId:
    Type: String
    Description: AWS Account ID for the Redshift Serverless workgroup
    Default: 80216656xxxx
    MinLength: 12
    MaxLength: 12
    AllowedPattern: "[0-9]{12}"
    ConstraintDescription: Must be a valid 12-digit AWS Account ID.

Resources:
  BedrockIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockRedshiftAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - redshift-data:ExecuteStatement
                  - redshift-data:GetStatementResult
                  - redshift-data:DescribeStatement
                  - redshift-data:CancelStatement
                  - redshift-serverless:GetCredentials
                  - redshift-serverless:GetWorkgroup
                  - redshift-serverless:GetNamespace
                  - redshift-serverless:DescribeWorkgroup
                Resource:
                  - !Ref WorkgroupArn
                  - !Sub "arn:aws:redshift-serverless:${AWS::Region}:${AccountId}:namespace/*"
                  - !Sub "arn:aws:redshift-serverless:${AWS::Region}:${AccountId}:database/*"
              - Effect: Allow
                Action:
                  - bedrock:GenerateQuery
                  - bedrock:Retrieve
                  - bedrock:RetrieveAndGenerate
                  - bedrock:GetKnowledgeBase
                  - bedrock:QueryKnowledgeBase
                  - bedrock:CreateDataSource
                  - bedrock:GetDataSource
                  - bedrock:UpdateDataSource
                Resource: "*"

  MyBedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    DependsOn: BedrockIAMRole
    Properties:
      Name: !Ref KnowledgeBaseName
      Description: A knowledge base for answering user queries using an existing Redshift Serverless workgroup
      RoleArn: !GetAtt BedrockIAMRole.Arn
      KnowledgeBaseConfiguration:
        Type: SQL
        SqlKnowledgeBaseConfiguration:
          Type: REDSHIFT
          RedshiftConfiguration:
            QueryEngineConfiguration:
              Type: SERVERLESS
              ServerlessConfiguration:
                WorkgroupArn: !Ref WorkgroupArn
                AuthConfiguration:
                  Type: IAM
            StorageConfigurations:
              - RedshiftConfiguration:
                  DatabaseName: !Ref DatabaseName
                Type: REDSHIFT
      Tags:
        Purpose: BedrockKnowledgeBase

  MyRedshiftDataSource:
    Type: AWS::Bedrock::DataSource
    DependsOn: MyBedrockKnowledgeBase
    Properties:
      KnowledgeBaseId: !Ref MyBedrockKnowledgeBase
      Name: !Ref DataSourceName
      Description: Data source for Redshift Serverless workgroup to enable query engine
      DataSourceConfiguration:
        Type: REDSHIFT
        RedshiftConfiguration:
          DatabaseName: !Ref DatabaseName
          WorkgroupArn: !Ref WorkgroupArn
          AuthConfiguration:
            Type: IAM

Outputs:
  KnowledgeBaseId:
    Description: ID of the Bedrock knowledge base
    Value: !Ref MyBedrockKnowledgeBase
  DataSourceId:
    Description: ID of the Bedrock data source
    Value: !GetAtt MyRedshiftDataSource.DataSourceId
  IAMRoleArn:
    Description: ARN of the IAM role for Bedrock Knowledge Base and Data Source
    Value: !GetAtt BedrockIAMRole.Arn
